os: linux
language: cpp
dist: bionic

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "prSAtsBHMML0TgCZqDh3SmHMAZsWNCdDdFmAFyZKR3OlSDfqnnfTuBwBy7OR9XEXUE5MAUPJrj3MFq9jT1yswt9sv2Ptm9zTu099HxMlpuW/SfOUsZIwUiVpChQGNK5yUjKAqJHv8HCosUIgy6nE2UzzitBQfvGZEzv9nRbBMCQ="

addons:
  apt:
    packages:
      - build-essential
      - git-core
      - cmake
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
      - libsqlcipher-dev
      - qtbase5-dev
      - qttools5-dev
      - libqt5svg5
  coverity_scan:
    project:
      name: "sqlitebrowser/sqlitebrowser"
      description: "DB4S"
    notification_email: github@mkleusberg.de
    build_command_prepend: "cov-configure --comptype gcc --compiler g++ --template;mkdir build; cd build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON .."
    build_command: "make VERBOSE=1"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - github@mkleusberg.de
    on_success: never
on_failure: always
